variables:
    CHECK_PROJECT: './src/Otus.Teaching.Pcf.ReceivingFromPartner/Otus.Teaching.Pcf.ReceivingFromPartner.WebHost/Otus.Teaching.Pcf.ReceivingFromPartner.WebHost.csproj'

stages:
    - build

build_Web.HttpAggregator_prj_job:
    stage: build
    image: mcr.microsoft.com/dotnet/sdk:6.0
    script:
        - dotnet build $CHECK_PROJECT -c Release -o content
    rules:   
      - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        changes:
        - ./src/Otus.Teaching.Pcf.ReceivingFromPartner/Otus.Teaching.Pcf.ReceivingFromPartner.WebHost/**/*
    artifacts:
        paths:
        - content